version: '3.3'
volumes:
  data:
services:
  db:
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laboratory
  laboratory:
    image: laboratory
    environment:
      - SPRING_PROFILE=local
    depends_on:
      - db
    command: java -jar app.jar -Xms256m -Xmx256m
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 1024M