spring:
  application:
    name: laboratory-service
  profiles:
    active: ${SPRING_PROFILE:local}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
  flyway:
    enabled: false
    locations: ["filesystem:src/main/resources/migrations", "classpath:/BOOT-INF/classes/migrations/"]
server:
  servlet:
    context-path: /laboratory-service